const mainTypes = Object.freeze({
    MAIN_UPDATE_MOVIES_LOADER: 'MAIN_UPDATE_MOVIES_LOADER',
    MAIN_LOAD_MOVIES_SUCCESS: 'MAIN_LOAD_MOVIES_SUCCESS',
    MAIN_UPDATE_FAVORITE_MOVIES_SUCCESS: 'MAIN_UPDATE_FAVORITE_MOVIES_SUCCESS',
    MAIN_UPDATE_OPTIONS_PANEL_DISPLAY: 'MAIN_UPDATE_OPTIONS_PANEL_DISPLAY',
    MAIN_UPDATE_MODAL_DATA: 'MAIN_UPDATE_MODAL_DATA',
    MAIN_SET_GENRES_LIST: 'MAIN_SET_GENRES_LIST'
});

export default mainTypes;