const formTypes = Object.freeze({
    FORM_SET_FORM_SUCCESS: 'FORM_SET_FORM_SUCCESS',
    FORM_SET_FORM_STATUS_SUCCESS: 'FORM_SET_FORM_STATUS_SUCCESS',
    FORM_SET_FORM_LEAVE_SUCCESS: 'FORM_SET_FORM_LEAVE_SUCCESS',
    FORM_INIT_EXISTS_FORM_SUCCESS: 'FORM_INIT_EXISTS_FORM_SUCCESS'
});

export default formTypes;