const mainTypes = Object.freeze({
    MAIN_SEARCH_TEXT_CHANGE_SUCCESS: 'MAIN_SEARCH_TEXT_CHANGE_SUCCESS',
    MAIN_LOAD_MOVIES_START: 'MAIN_LOAD_MOVIES_START',
    MAIN_LOAD_MOVIES_SUCCESS: 'MAIN_LOAD_MOVIES_SUCCESS',
    MAIN_UPDATE_FAVORITE_MOVIES_SUCCESS: 'MAIN_UPDATE_FAVORITE_MOVIES_SUCCESS',
    // SAGAS
    MAIN_LOAD_MOVIES: 'MAIN_LOAD_MOVIES',
    MAIN_SEARCH_TEXT_CHANGE: 'MAIN_SEARCH_TEXT_CHANGE',
    MAIN_UPDATE_FAVORITE_MOVIES: 'MAIN_UPDATE_FAVORITE_MOVIES'
});

export default mainTypes;